### PR TITLE
Enable compilation for GCC > 4

### PR DESCRIPTION
**Pull request by schoppmp**
Tested with GCC 7.2.0 and clang 5.0.0

### CODE REVIEW

**Comment by johannesthoma** [comment]
Thanks for your patch. Did make test run successfully?

**Comment by schoppmp** [comment]
I did, [here's the output](https://github.com/johannesthoma/mmap_allocator/files/1463691/test.txt). However, I'm not sure how exactly to do the tests with strace. There are some messages regarding this in the output.

**Comment by johannesthoma** [comment]
The strace was for something I currently don't remember, I suppose it is still working since you didn't touch that part. Thanks again for the pull request are you using mmap_allocator in one of your projects (just because I am curious)?

**Comment by schoppmp** [comment]
I haven't really decided yet, it's either mmap_allocator or [boost::interprocess managed mapped files](http://www.boost.org/doc/libs/1_65_1/doc/html/interprocess/managed_memory_segments.html#interprocess.managed_memory_segments.managed_mapped_files). Not sure what I will end up with eventually.

**Pull request merged**
